server:
  port: 8025

spring:
  application:
    name: cloud-register-gateway-zuul-filter

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/

# 打印日志
logging:
  level:
    root: INFO
    com.springms: DEBUG
    com.netflix: debug

