server:
  port: 8050

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          #git地址
          uri: https://gitee.com/StarskyBoy/cloud-config-repo
          #git用户名
          username: ******
          #git密码
          password: ******
