server:
  port: 8030

spring:
  application:
    name: cloud-register-gateway-zuul-aggregation

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true


