server:
  port: 8029

spring:
  application:
    name: cloud-sidecar-client-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true


