server:
  port: 8017

spring:
  application:
    name: cloud-register-consumer-feign-logger

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
   com.midou.cloud.register.consumer.feign.logger.dao.UserFeignClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。


