server:
  port: 8016

spring:
  application:
    name: cloud-register-consumer-ribbon-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true


