server:
  port: 8018

spring:
  application:
    name: cloud-register-consumer-feign-hystrix-fallback-factory

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true


