server:
  port: 8052

spring:
  application:
    name: cloud-config-server-refresh-cloud-bus
  cloud:
    config:
      server:
        git:
          #git地址
          uri: https://gitee.com/StarskyBoy/cloud-config-repo
          #git用户名
          username: ******
          #git密码
          password: ******
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.43.37
    port: 5672
    username: admin
    password: admin

management:
  security:
    enabled: false
